### ISSUE TITLE
Unit Test Framework Suggestion for Java

### ISSUE THREAD

**Issue by xorz57** [arkoydas/Aueb_projects#2]
Για επισημα Unit Tests μπορεις να χρησιμοποιησεις το [JUnit 5](http://junit.org/junit5/) για τη Java
Δες tutorials στο youtube αν σε ενδιαφερει.
Καλη Δουλεια εχεις κανει βλεπω ;)

**Comment by arkoydas** [comment]
Γεια σου xorz57, θα του ριξω μια ματιά αυριο.
Αν εχεις κατι αλλο ενδιαφερον παρακαλω να μου το πεις.
Σε ευχαριστώ πολύ για το ενδιαφέρον σου.
